<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Game;


class GameSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $indieGames = [
            ["id" => 1, "name" => "Hollow Knight", "developer" => "Team Cherry", "genre" => "Metroidvania", "graphics_style" => "2D Hand-drawn", "release_year" => "2017", "description" => "Explora el vasto reino interconectado de Hallownest. Enfrenta a más de 150 enemigos y jefes épicos en un mundo melancólico.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg", "steam_url" => "https://store.steampowered.com/app/367520/Hollow_Knight/"],
            ["id" => 2, "name" => "Celeste", "developer" => "Maddy Makes Games", "genre" => "Platformer", "graphics_style" => "2D Pixel Art", "release_year" => "2018", "description" => "Un plataformas de precisión que narra el viaje emocional de Madeline contra su propia ansiedad.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/504230/header.jpg", "steam_url" => "https://store.steampowered.com/app/504230/Celeste/"],
            ["id" => 3, "name" => "Stardew Valley", "developer" => "ConcernedApe", "genre" => "Simulation", "graphics_style" => "2D Pixel Art", "release_year" => "2016", "description" => "Hereda la vieja parcela de tu abuelo y devuélvele la gloria en este simulador de granja.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg", "steam_url" => "https://store.steampowered.com/app/413150/Stardew_Valley/"],
            ["id" => 4, "name" => "Blasphemous", "developer" => "The Game Kitchen", "genre" => "Metroidvania", "graphics_style" => "2D Pixel Art", "release_year" => "2019", "description" => "Acción brutal y oscura en la tierra de Cvstodia inspirada en el folclore religioso.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/774361/header.jpg", "steam_url" => "https://store.steampowered.com/app/774361/Blasphemous/"],
            ["id" => 5, "name" => "Undertale", "developer" => "Toby Fox", "genre" => "RPG", "graphics_style" => "2D Pixel Art", "release_year" => "2015", "description" => "El RPG donde nadie tiene que morir. Cada decisión afecta permanentemente la historia.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/391540/header.jpg", "steam_url" => "https://store.steampowered.com/app/391540/Undertale/"],
            ["id" => 6, "name" => "Dead Cells", "developer" => "Motion Twin", "genre" => "Roguelite", "graphics_style" => "2D Pixel Art", "release_year" => "2018", "description" => "Un Rogue-lite frenético con combate tipo Souls en un castillo en constante cambio.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/588650/header.jpg", "steam_url" => "https://store.steampowered.com/app/588650/Dead_Cells/"],
            ["id" => 7, "name" => "Hyper Light Drifter", "developer" => "Heart Machine", "genre" => "Action RPG", "graphics_style" => "2D Pixel Art", "release_year" => "2016", "description" => "Explora un mundo en ruinas lleno de peligros y tecnología olvidada con visuales neón.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/257850/header.jpg", "steam_url" => "https://store.steampowered.com/app/257850/Hyper_Light_Drifter/"],
            ["id" => 8, "name" => "Terraria", "developer" => "Re-Logic", "genre" => "Sandbox", "graphics_style" => "2D Pixel Art", "release_year" => "2011", "description" => "Cava, lucha, explora y construye en este sandbox de acción infinita.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/105600/header.jpg", "steam_url" => "https://store.steampowered.com/app/105600/Terraria/"],
            ["id" => 9, "name" => "Shovel Knight", "developer" => "Yacht Club Games", "genre" => "Platformer", "graphics_style" => "2D Pixel Art", "release_year" => "2014", "description" => "Una carta de amor a los juegos de 8 bits con una pala como arma principal.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/250760/header.jpg", "steam_url" => "https://store.steampowered.com/app/250760/Shovel_Knight_Treasure_Trove/"],
            ["id" => 10, "name" => "Enter the Gungeon", "developer" => "Dodge Roll", "genre" => "Bullet Hell", "graphics_style" => "2D Pixel Art", "release_year" => "2016", "description" => "Dungeon crawler donde buscas el arma que puede matar el pasado.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/311690/header.jpg", "steam_url" => "https://store.steampowered.com/app/311690/Enter_the_Gungeon/"],
            ["id" => 11, "name" => "Papers, Please", "developer" => "Lucas Pope", "genre" => "Puzzle", "graphics_style" => "2D Pixel Art", "release_year" => "2013", "description" => "Thriller documental sobre la burocracia de un estado totalitario. ¡Gloria a Arstotzka!", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/239030/header.jpg", "steam_url" => "https://store.steampowered.com/app/239030/Papers_Please/"],
            ["id" => 12, "name" => "Katana ZERO", "developer" => "Askiisoft", "genre" => "Action", "graphics_style" => "2D Pixel Art", "release_year" => "2019", "description" => "Acción neo-noir vertiginosa con manipulación del tiempo y muerte instantánea.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/460950/header.jpg", "steam_url" => "https://store.steampowered.com/app/460950/Katana_ZERO/"],
            ["id" => 13, "name" => "The Messenger", "developer" => "Sabotage Studio", "genre" => "Action Platformer", "graphics_style" => "2D Pixel Art", "release_year" => "2018", "description" => "Un ninja debe entregar un pergamino mientras el juego salta entre 8 y 16 bits.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/764790/header.jpg", "steam_url" => "https://store.steampowered.com/app/764790/The_Messenger/"],
            ["id" => 14, "name" => "Owlboy", "developer" => "D-Pad Studio", "genre" => "Platformer", "graphics_style" => "2D Pixel Art", "release_year" => "2016", "description" => "Aventura de plataformas voladoras con un pixel art increíblemente detallado.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/115800/header.jpg", "steam_url" => "https://store.steampowered.com/app/115800/Owlboy/"],
            ["id" => 15, "name" => "Eastward", "developer" => "Pixpil", "genre" => "Adventure", "graphics_style" => "2D Pixel Art", "release_year" => "2021", "description" => "Viaje post-apocalíptico detallado inspirado en los clásicos RPG de los 90.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/977880/header.jpg", "steam_url" => "https://store.steampowered.com/app/977880/Eastward/"],
            ["id" => 16, "name" => "Hades", "developer" => "Supergiant Games", "genre" => "Roguelike", "graphics_style" => "Isometric 3D", "release_year" => "2020", "description" => "Desafía al Dios de los Muertos y escapa del Inframundo con bendiciones del Olimpo.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg", "steam_url" => "https://store.steampowered.com/app/1145360/Hades/"],
            ["id" => 17, "name" => "Outer Wilds", "developer" => "Mobius Digital", "genre" => "Exploration", "graphics_style" => "3D Stylized", "release_year" => "2019", "description" => "Misterio de mundo abierto sobre un sistema solar atrapado en un bucle temporal.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753640/header.jpg", "steam_url" => "https://store.steampowered.com/app/753640/Outer_Wilds/"],
            ["id" => 18, "name" => "Firewatch", "developer" => "Campo Santo", "genre" => "Adventure", "graphics_style" => "3D Stylized", "release_year" => "2016", "description" => "Henry busca escapar de su vida trabajando como vigilante de incendios en los bosques.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/383870/header.jpg", "steam_url" => "https://store.steampowered.com/app/383870/Firewatch/"],
            ["id" => 19, "name" => "Journey", "developer" => "thatgamecompany", "genre" => "Adventure", "graphics_style" => "3D Stylized", "release_year" => "2012", "description" => "Viaje anónimo a través de un desierto infinito hacia una montaña lejana.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/638230/header.jpg", "steam_url" => "https://store.steampowered.com/app/638230/Journey/"],
            ["id" => 20, "name" => "Sable", "developer" => "Shedworks", "genre" => "Exploration", "graphics_style" => "3D Cel-shaded", "release_year" => "2021", "description" => "Rito de iniciación a través de vastos desiertos en una moto voladora.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/757310/header.jpg", "steam_url" => "https://store.steampowered.com/app/757310/Sable/"],
            ["id" => 21, "name" => "Subnautica", "developer" => "Unknown Worlds", "genre" => "Survival", "graphics_style" => "3D Realistic", "release_year" => "2018", "description" => "Supervivencia en un planeta oceánico lleno de criaturas colosales.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/264710/header.jpg", "steam_url" => "https://store.steampowered.com/app/264710/Subnautica/"],
            ["id" => 22, "name" => "Tunic", "developer" => "Andrew Shouldice", "genre" => "Action Adventure", "graphics_style" => "Isometric 3D", "release_year" => "2022", "description" => "Un pequeño zorro en una gran aventura isométrica llena de secretos.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/553420/header.jpg", "steam_url" => "https://store.steampowered.com/app/553420/TUNIC/"],
            ["id" => 23, "name" => "Valheim", "developer" => "Iron Gate Studio", "genre" => "Survival", "graphics_style" => "3D Low Poly", "release_year" => "2021", "description" => "Brutal juego de supervivencia vikinga en un mundo generado procedimentalmente.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/892970/header.jpg", "steam_url" => "https://store.steampowered.com/app/892970/Valheim/"],
            ["id" => 24, "name" => "Risk of Rain 2", "developer" => "Hopoo Games", "genre" => "Roguelike", "graphics_style" => "3D Stylized", "release_year" => "2020", "description" => "Escapa de un planeta hostil luchando contra hordas de monstruos que escalan en poder.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/632360/header.jpg", "steam_url" => "https://store.steampowered.com/app/632360/Risk_of_Rain_2/"],
            ["id" => 25, "name" => "Kena: Bridge of Spirits", "developer" => "Ember Lab", "genre" => "Action Adventure", "graphics_style" => "3D Stylized", "release_year" => "2021", "description" => "Guía espiritual que restaura una aldea con la ayuda de los adorables Rot.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1954200/header.jpg", "steam_url" => "https://store.steampowered.com/app/1954200/Kena_Bridge_of_Spirits/"],
            ["id" => 26, "name" => "The Witness", "developer" => "Thekla, Inc.", "genre" => "Puzzle", "graphics_style" => "3D Realistic", "release_year" => "2016", "description" => "Despiertas solo en una isla llena de puzles complejos basados en el lenguaje visual.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/210970/header.jpg", "steam_url" => "https://store.steampowered.com/app/210970/The_Witness/"],
            ["id" => 27, "name" => "Neon White", "developer" => "Angel Matrix", "genre" => "FPS", "graphics_style" => "3D Stylized", "release_year" => "2022", "description" => "FPS ultra rápido donde usas cartas de armas para moverte y atacar en el cielo.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1533420/header.jpg", "steam_url" => "https://store.steampowered.com/app/1533420/Neon_White/"],
            ["id" => 28, "name" => "Stray", "developer" => "BlueTwelve Studio", "genre" => "Adventure", "graphics_style" => "3D Realistic", "release_year" => "2022", "description" => "Un gato callejero explora una ciber-ciudad olvidada habitada por robots.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1332010/header.jpg", "steam_url" => "https://store.steampowered.com/app/1332010/Stray/"],
            ["id" => 29, "name" => "Slime Rancher", "developer" => "Monomi Park", "genre" => "Adventure", "graphics_style" => "3D Stylized", "release_year" => "2017", "description" => "Explora un planeta alienígena criando slimes coloridos en tu propio rancho.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/433340/header.jpg", "steam_url" => "https://store.steampowered.com/app/433340/Slime_Rancher/"],
            ["id" => 30, "name" => "Cuphead", "developer" => "Studio MDHR", "genre" => "Run and Gun", "graphics_style" => "2D Cartoon", "release_year" => "2017", "description" => "Inspirado en los dibujos de 1930 con animación tradicional y dificultad legendaria.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/268910/header.jpg", "steam_url" => "https://store.steampowered.com/app/268910/Cuphead/"],
            ["id" => 31, "name" => "Spiritfarer", "developer" => "Thunder Lotus Games", "genre" => "Management", "graphics_style" => "2D Hand-drawn", "release_year" => "2020", "description" => "Acogedor juego sobre la muerte donde guías espíritus hacia el más allá.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/972660/header.jpg", "steam_url" => "https://store.steampowered.com/app/972660/Spiritfarer/"],
            ["id" => 32, "name" => "Inside", "developer" => "Playdead", "genre" => "Puzzle-Platformer", "graphics_style" => "2.5D Stylized", "release_year" => "2016", "description" => "Un niño se ve arrastrado al centro de un proyecto oscuro y distópico.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/304430/header.jpg", "steam_url" => "https://store.steampowered.com/app/304430/INSIDE/"],
            ["id" => 33, "name" => "Limbo", "developer" => "Playdead", "genre" => "Puzzle-Platformer", "graphics_style" => "2D Silhouette", "release_year" => "2010", "description" => "Un niño entra en el Limbo buscando el destino de su hermana.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/48000/header.jpg", "steam_url" => "https://store.steampowered.com/app/48000/LIMBO/"],
            ["id" => 34, "name" => "Gris", "developer" => "Nomada Studio", "genre" => "Platformer", "graphics_style" => "2D Watercolor", "release_year" => "2018", "description" => "Un viaje artístico de introspección y dolor a través de un mundo acuarela.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/683320/header.jpg", "steam_url" => "https://store.steampowered.com/app/683320/GRIS/"],
            ["id" => 35, "name" => "Slay the Spire", "developer" => "MegaCrit", "genre" => "Deckbuilder", "graphics_style" => "2D Hand-drawn", "release_year" => "2019", "description" => "La fusión definitiva de cartas y roguelike. Escala la torre con un mazo único.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/646570/header.jpg", "steam_url" => "https://store.steampowered.com/app/646570/Slay_the_Spire/"],
            ["id" => 36, "name" => "Disco Elysium", "developer" => "ZA/UM", "genre" => "RPG", "graphics_style" => "Isometric Painted", "release_year" => "2019", "description" => "RPG de investigación policial donde interactúas con tu propia psique.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/632470/header.jpg", "steam_url" => "https://store.steampowered.com/app/632470/Disco_Elysium/"],
            ["id" => 37, "name" => "Cult of the Lamb", "developer" => "Massive Monster", "genre" => "Roguelike", "graphics_style" => "2D Stylized", "release_year" => "2022", "description" => "Crea tu propia secta y gestiona una comunidad de seguidores adorables.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1313140/header.jpg", "steam_url" => "https://store.steampowered.com/app/1313140/Cult_of_the_Lamb/"],
            ["id" => 38, "name" => "Inscryption", "developer" => "Daniel Mullins Games", "genre" => "Roguelike", "graphics_style" => "Mixed Styles", "release_year" => "2021", "description" => "Odisea negra de cartas que mezcla el horror psicológico y puzles.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1092790/header.jpg", "steam_url" => "https://store.steampowered.com/app/1092790/Inscryption/"],
            ["id" => 39, "name" => "Don't Starve", "developer" => "Klei Entertainment", "genre" => "Survival", "graphics_style" => "2D Hand-drawn", "release_year" => "2013", "description" => "Supervivencia extrema en un mundo salvaje lleno de ciencia y magia.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/219740/header.jpg", "steam_url" => "https://store.steampowered.com/app/219740/Dont_Starve/"],
            ["id" => 40, "name" => "Hades II", "developer" => "Supergiant Games", "genre" => "Roguelike", "graphics_style" => "Isometric 3D", "release_year" => "2024", "description" => "Hechicería oscura y lucha contra el Titán del Tiempo en esta esperada secuela.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145350/header.jpg", "steam_url" => "https://store.steampowered.com/app/1145350/Hades_II/"],
            ["id" => 41, "name" => "Vampire Survivors", "developer" => "poncle", "genre" => "Roguelite", "graphics_style" => "2D Pixel Art", "release_year" => "2022", "description" => "Sobrevive a hordas masivas de monstruos en este juego de acción minimalista.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1794680/header.jpg", "steam_url" => "https://store.steampowered.com/app/1794680/Vampire_Survivors/"],
            ["id" => 42, "name" => "Dave the Diver", "developer" => "MINTROCKET", "genre" => "Adventure", "graphics_style" => "Pixel Art/3D", "release_year" => "2023", "description" => "Pesca de día y gestiona un restaurante de sushi de noche.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1868140/header.jpg", "steam_url" => "https://store.steampowered.com/app/1868140/DAVE_THE_DIVER/"],
            ["id" => 43, "name" => "Animal Well", "developer" => "Billy Basso", "genre" => "Metroidvania", "graphics_style" => "2D Pixel Art", "release_year" => "2024", "description" => "Laberinto denso y atmosférico lleno de secretos y animales reactivos.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/813230/header.jpg", "steam_url" => "https://store.steampowered.com/app/813230/ANIMAL_WELL/"],
            ["id" => 44, "name" => "Balatro", "developer" => "LocalThunk", "genre" => "Roguelike", "graphics_style" => "2D Pixel Art", "release_year" => "2024", "description" => "Roguelike de póker donde usas comodines únicos para hacer trampas legales.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2379780/header.jpg", "steam_url" => "https://store.steampowered.com/app/2379780/Balatro/"],
            ["id" => 45, "name" => "Sanctuary Saga", "developer" => "Orbis", "genre" => "RPG", "graphics_style" => "2D Pixel Art", "release_year" => "2023", "description" => "Combates por turnos centrados en la posición y gestión de relaciones.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1582200/header.jpg", "steam_url" => "https://store.steampowered.com/app/1582200/Sanctuary_Saga/"],
            ["id" => 46, "name" => "Braid", "developer" => "Number None", "genre" => "Puzzle-Platformer", "graphics_style" => "2D Painted", "release_year" => "2008", "description" => "Manipulación del tiempo para resolver puzles existenciales.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/26800/header.jpg", "steam_url" => "https://store.steampowered.com/app/26800/Braid/"],
            ["id" => 47, "name" => "Fez", "developer" => "Polytron Corporation", "genre" => "Puzzle-Platformer", "graphics_style" => "2D/3D Mixed", "release_year" => "2012", "description" => "Rota un mundo 2D para descubrir una tercera dimensión.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/224760/header.jpg", "steam_url" => "https://store.steampowered.com/app/224760/FEZ/"],
            ["id" => 48, "name" => "Cave Story", "developer" => "Studio Pixel", "genre" => "Action Adventure", "graphics_style" => "2D Pixel Art", "release_year" => "2004", "description" => "Clásico atemporal que definió la estructura de los juegos indie modernos.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/200900/header.jpg", "steam_url" => "https://store.steampowered.com/app/200900/Cave_Story/"],
            ["id" => 49, "name" => "Spelunky 2", "developer" => "Mossmouth", "genre" => "Roguelike", "graphics_style" => "2D Cartoon", "release_year" => "2020", "description" => "Exploración extrema de cuevas lunares llenas de trampas mortales.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/418530/header.jpg", "steam_url" => "https://store.steampowered.com/app/418530/Spelunky_2/"],
            ["id" => 50, "name" => "Pizza Tower", "developer" => "Tour De Pizza", "genre" => "Platformer", "graphics_style" => "2D Cartoon", "release_year" => "2023", "description" => "Plataformas veloz inspirado en Wario Land con animación caótica.", "image_path" => "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2231450/header.jpg", "steam_url" => "https://store.steampowered.com/app/2231450/Pizza_Tower/"],
        ];

        foreach ($indieGames as $game) {
            Game::create($game);
        }
    }
}
